jurplel/install-qt-action

- src/main.ts
This pull request updates `main.ts` to use the Qt recommended command to install the additional requirements for Linux.
Related to #3, I think the basic build requirements should be installed by the action. According to [Qt's documentation, the Qt installer assumes](https://doc.qt.io/qt-5/linux.html#requirements-for-development-host):
> that a C++ compiler, debugger, make, and other development tools are provided by the host operating system. In addition, building graphical Qt applications requires OpenGL libraries and headers installed
Having the `install-qt-action` perform this installation means end-developers using this action don't need to account for it in their workflow (which makes matrix building a little less complicated as these additional requirements for Linux don't apply to …
> On Linux, install basic build requirements for desktop applications.

- .github/workflows/test.yml
- README.md
- src/main.ts
This PR adds support for aqtisntaller module input. This is a new feature since version 0.6a1, see miurahr/aqtinstall#68. 
Also, added the pip --pre flag to get the current pre-release version of aqtinstaller (0.6a2), which introduces a bug fix for the the issue mentioned in #6 and also the qt module support.
Not sure if it works with multiple module inputs such as `-m qtcharts qtnetworkauth`.
Changed the test to include the module flag and to be also triggered by incoming PRs.
Not sure if my code works :) Please let me know what you think.
> Use pip --pre and support for Qt modules

- .github/workflows/test.yml
- README.md
- src/main.ts
Support cache, close #22.
Example of using cache:
```yaml
- name: Cache Qt
id: cache-qt
uses: actions/cache@v1
with:
path: ../Qt
key: QtCache
- name: Install Qt
uses: repo/install-qt-action@version
with:
cached: ${{ steps.cache-qt.outputs.cache-hit }}
```
---
Use arch for windows and android only, fixes #25.
---
Customizable aqtinstall version, solves problems like #27.
> Support cache & Use arch for windows and android only & Customizable aqt version

- src/main.ts
I'm using your action in our pipeline and faced an issue (very similar to https://github.com/microsoft/azure-pipelines-image-generation/issues/897)
The problem I've faced is that binaries on linux machine to which I've installed QT by their official installer worked fine but binaries from CI pipeline (16-04 worker) doesn't start on linux with:
```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Aborted (core dumped)
```
So I've relaised that https://github.com/probonopd/linuxdeployqt we using for deploy doesn't attach plugins by some reason
I've started to dig and in CI build logs …
> add libxkbcommon-x11-0 to linux deps

- package-lock.json
- package.json
- src/main.ts
this might help to fix issue #43
compare-versions supports incomplete version numbers like 5.5 (instead of 5.5.1)
Attention, as I have no clue about the scripting languages you use here: please carefully review my suggested changes!
> migrate from semver to compare-versions

- src/main.ts
This makes sure that "pip3 install" and "python3" refer to the same python version.
Supposed to fix #60.
> Always call pip via python -m pip

- .github/workflows/test.yml
See:
- actions/virtual-environments#3287
- [GitHub Actions : Ubuntu 16.04 LTS virtual environment will be removed on September 20, 2021 | GitHub Changelog](https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/).
> CI (GitHub Actions): drop the Ubuntu 16.04 environment

- .github/workflows/test.yml
It seems that actions/checkout@v1 is buggy when checking out from PRs. Let's try v2.
https://github.com/jurplel/install-qt-action/runs/3704315556?check_suite_focus=true
```console
> Run actions/checkout@v1
Syncing repository: jurplel/install-qt-action
git version
git version 2.33.0.windows.2
git lfs version
git-lfs/2.13.3 (GitHub; windows amd64; go 1.16.2; git a5e65851)
git init "D:\a\install-qt-action\install-qt-action"
Initialized empty Git repository in D:/a/install-qt-action/install-qt-action/.git/
git remote add origin https://github.com/jurplel/install-qt-action
git config gc.auto 0
git config --get-all http.https://github.com/jurplel/install-qt-action.extraheader
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --tags --prune --progress --no-recurse-submodules origin …
```
> CI (GitHub Actions): try actions/checkout@v2

- .github/workflows/test.yml
- README.md
- action.yml
- src/main.ts
This is my attempt at updating the action to use the 2.0.0 release of `aqtinstall`.
Fix #114. `aqt` v2.0.0 allows you to install tools without specifying a tool version number, so the syntax of the `tool` field is changed. I made an effort to maintain backwards compatibility though, so this PR will simply ignore the version number if you put it in:
```yml
tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'                                # new syntax
tools: 'tools_ifw,4.1.1,qt.tools.ifw.41 tools_qtcreator,5.0.1-0,qt.tools.qtcreator'  # still works
```
This is also a step towards fixing #98. `aqt` 2.0.0 allows you to use a SimpleSpec to specify a Qt version; to install the latest 5.12 you would use `aqt install-qt windows desktop 5.12 <arch>`.
**Please note:** aqtinstall 2.0.0 introduces …
> Use aqtinstall v2.0.0

- package-lock.json
- package.json
Fix #116.
This eliminates two errors in the "npm run build" step on Windows. It does not attempt to cause the build to fail when `npm run *` commands fail; this appears to be an intractable issue with powershell: see https://github.com/jurplel/install-qt-action/issues/116#issuecomment-933384134.
Successful run of this PR: https://github.com/ddalcino/install-qt-action/actions/runs/1373216276
> Use same devDependencies as `setup-python`

- .github/workflows/test.yml
- src/main.ts
This PR uses the Node standard library `path` module to convert paths into the native format on every platform.
This action sets several environment variables that include paths. On Windows, many of these paths include `/` instead of `\`, or use some mix of both: 
Example from: https://github.com/jurplel/install-qt-action/runs/3916210538?check_suite_focus=true#step:7:10 
```
shell: C:\Windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
env:
pythonLocation: C:\hostedtoolcache\windows\Python\3.10.0\x64
IQTA_TOOLS: D:\a\install-qt-action/Qt/Tools
Qt5_Dir: D:/a/install-qt-action/Qt/5.9/msvc2017_64
QT_PLUGIN_PATH: D:/a/install-qt-action/Qt/5.9/msvc2017_64/plugins
QML2_IMPORT_PATH: D:/a/install-qt-action/Qt/5.9/msvc2017_64/qml
```
On Windows, many programs are resilient to this kind of …
> Fix directory separators in environment variables on Windows

- .github/workflows/test.yml
- README.md
- tests/TestWithModules/TestWithModules.pro
This adds Qt 6.2.0 to the test workflow.
I am using #119 as a base for this because I am not certain that aqt 1.2.5 installs modules properly. I think v1.2.5 can install the `qtwebengine` module if you call it `addons.qtwebengine`, but that solution is not so nice. With aqt v2 you can just call it `qtwebengine`.
I have observed that when you run `qmake` on a project that requests the `webengine` module, it doesn't work on Qt 6, no matter what modules are installed. I believe that the solution is to use `webenginewidgets` or `webenginecore` in the test `.pro` file. See [Qt WebEngine Examples](https://doc.qt.io/qt-6.2/webengine-widgetexamples.html) and a [specific example](https://code.qt.io/cgit/qt/qtwebengine.git/tree/examples/webenginewidgets/contentmanipulation/CMakeLists.txt). …
> Add Qt 6.2 to test suite

- .github/workflows/test.yml
- action/src/main.ts
Fix #165
**Edit:** Added tests for a `tools-only` run, as requested here: https://github.com/jurplel/install-qt-action/issues/165#issuecomment-1399954593. The `tools-only` test is relevant because this PR modifies code that could potentially trigger errors in a `tools-only` run.
As a side effect, this should fix #115.
> Fix detection of Qt architecture directory

- .github/workflows/test.yml
- action/src/main.ts
This change allows `aqtinstall` to override the default or requested version of py7zr, in the event that the default or requested version is not compatible with the requested version of `aqtinstall`.
IMHO the user should not ever need to know anything about the `py7zr` dependency, and this action should just install aqtinstall properly, no matter what. This change should guarantee that.
Fix #176
> Install py7zr compatible with requested aqtinstall, no matter what

- .github/workflows/test.yml
- README.md
- action.yml
- action/action.yml
- action/src/main.ts
Fix #87
The code for installing source is very similar to the code that installs examples and docs, so I went ahead and implemented all of them.
This PR probably includes more refactoring than it should, but I was careful to keep all the refactors in their own commits, in case you want to move them to a separate PR. This PR would be too tedious for me to write without using these refactors, so they're included anyway.
* a6c6d1138781b492d3c5764fa58c762a77804d1d
* 9307e28277dcad7f866fdd95b8753852f90d3d0e
* a4367ae45f326b147864156266e3c9881568ddbc
* 22b24469d9cbcdd6ca55c005759af6819a280087
Please see the changes to the README.md for a discussion of all the new features added here.
> Add options to install source, docs, and examples

- .github/workflows/test.yml
- README.md
- README_upgrade_guide.md
- action/src/main.ts
- tests/TestWithModules/CMakeLists.txt
Fix #184.
This adds the `QT_ROOT_DIR` environment variable that takes the place of the old `Qt5_DIR` and `Qt6_DIR` variables, and points `Qt5_DIR` to the location that CMake expects.
Breaking changes are documented in the `README_upgrade_guide.md` file.
Please be aware that this is not a bug fix. I added a `CMakeLists.txt` file to the test project, so that each test run can configure a test project with CMake; these tests were passing before I made any code changes. The changes here are meant to make the action easier for users to understand:
* The `Qt5_DIR` is now given the value that it would need to have to run CMake properly, if the qmake directory had not been added to the path.
* The `Qt5_Dir` and `Qt6_DIR` variables have been removed, since they have no intrinsic purpose other than …
> [v4] Fix `Qt5_DIR` environment variable

- .github/workflows/test-android.yml
- README.md
- README_upgrade_guide.md
- action.yml
- action/action.yml
- action/src/main.ts
Fix #181. This will allow both mobile and WASM builds to succeed, when using Qt 6.2+. These new versions of Qt require a parallel installation of the desktop version of Qt, installed alongside the mobile or WASM versions.
As a side effect, this PR also fixes a logic bug in the way the `arch` input is set by default. When the user does not select an arch on Windows, and the target is set to `android`, the action selects a Windows desktop arch instead of an android arch. The change that fixes this issue is in its own commit: 8cd6038e549907ed4b1a590f662432496adb48a1
This PR makes breaking changes, discussed in the new `README_upgrade_guide.md` file. For that reason, this change should not be merged into v3 of this action.
This PR uses #179 as a starting point. I needed to use an example …
> [v4] Install desktop Qt when required to by Qt 6.2+ mobile and WASM

- .github/workflows/test.yml
- README.md
- README_upgrade_guide.md
- action.yml
- action/action.yml
- action/src/main.ts
- action/tsconfig.json
Fix #157 
As discussed in #157, the preferred way to handle this is to append tool paths to the PATH, so that the added paths don't unintentionally override other tools that you're trying to keep in your environment. The tools provided by aqtinstall tend to include a lot of binaries that you may or may not actually need.
Unfortunately, every attempt I have made to append tool paths has failed miserably on Windows. Github toolkit/core provides a convenient and robust method of prepending to the path, and that's what this PR uses, because it works really well. Unfortunately, Github did not provide an equivalent "append to path" method that works on Windows, and nothing I have tried has worked so far.
I am submitting this as a draft because it prepends to the path, rather than appends. …
> [v4] Add installed tools to path

- action/lib/main.js
- action/src/main.ts
Windows on ARM also requires a standard desktop Qt installation, however when attempting to use this action with arm, the desktop paths are set instead.
This PR fixes this issue by preferring `msvc*_arm64` versions of Qt (the same way `android*`, `ios` and `wasm*` versions are preferred.
> Add Windows ARM support

- .github/workflows/test-android.yml
- .github/workflows/test.yml
- action.yml
- action/action.yml
This PR completes #219 and fixes #220 .
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, actions/setup-python@v4, ./action. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> Update node.js version to 20; update CI dependencies to remove warnings

- action/src/main.ts
Starting Qt 6.5.0, the XCB platform plugin for Linux/X11 also depends on `xcb-cursor0` at runtime, logging as much if the compiled application is started without it being present:
```
from 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin. 
Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
To resolve this in cases where the application needs to be run within the actions workflow, this PR add the requisite Ubuntu package to the dependency packages installed by the action.
> Add libxcb-cursor0 to Linux dependencies for Qt 6.5 and up

- README.md
- action.yml
- action/.eslintrc.js
- action/action.yml
- action/src/main.ts
In the case where upstream aqtinstall breaks, or is somehow inadequate for a particular use case, it's helpful to be able to point the action at a different repository. This change facilitates this, via the new 'aqtsource' option, whose value is passed directly to pip install when set. When unset the usual aqtinstall+$aqtversion value is used.
> Add 'aqtsource' option that allows overriding where the action sources aqtinstall from

- README.md
Now, the "v4" branch is newer than "master". It's a bit confusing.
> Update the version number to v4 in the example

- action/src/main.ts
https://github.com/jurplel/install-qt-action/issues/244
> p7zip is preinstalled in macos

- README.md
- action/src/main.ts
Qt switched to MSVC 2022
Fixes #250
> Fix installing Qt6 6.8.0 on Windows

- .github/workflows/test.yml
- action/src/main.ts
Fix #255.
This PR fixes the behavior of the `add-tools-to-path` option for a few tools where it currently does not work. These tools include:
* Ninja: this tool installs at `Tools/Ninja/ninja`
* Conan: this tool installs at `Tools/Conan/conan`
* CMake: On MacOS, this tool installs at `Tools/CMake/CMake.app`, which is not where `install-qt-action` currently looks for it, parallel to the `Tools` directory.
This PR also adds tests to check that these tools are installed, executable, and in the PATH when `add-tools-to-path` is set.
It is still possible that there are other tools somewhere in the Qt repo that aren't being added to the PATH properly; I have not exhaustively searched them. If there are more such tools, it should not be too difficult to modify this code to fix them.
> Add missing tool paths to the PATH

- action/src/main.ts
I propose a small change so that Qt 6.7.3 can use msvc2022. This will not prevent Qt 6.8.0 from using msvc2022.
> Ability to use msvc2022 for Qt 6.7.3

- .github/workflows/test-android.yml
- .github/workflows/test.yml
MacOS-12 images are deprecated and will be removed next month.
See https://github.com/actions/runner-images/issues/10721 for details.
> Update deprecated macOS-12 to macOS-15

- action/src/main.ts
This reverts commit b9760ab01f548abc52e3649b6ec31dbecfe229d0 (https://github.com/jurplel/install-qt-action/pull/257).
`aqtinstall` doesn't provide a `win64_msvc2022_64`:
```console
> aqt list-qt windows desktop --arch 6.7.3
win64_llvm_mingw win64_mingw win64_msvc2019_64 win64_msvc2019_arm64
```
> Revert "Use msvc2022 for Qt 6.7.3"

- .github/workflows/test.yml
- action/src/main.ts
Fix #259.
Currently, this action relies heavily on string manipulation techniques to compose paths. This approach is prone to error, particularly in the context of Windows and inconsistent use of native path delimiters. This PR uses the standard Node `path` library to manipulate paths.
* Link to test run that replicates #259, using the install directory `/` and test runner `windows-latest`: https://github.com/ddalcino/install-qt-action/actions/runs/11786060831/job/32828603078#step:9:1
Note the broken environment variables:
```
IQTA_TOOLS: \\Qt\Tools\
QT_ROOT_DIR: D:\Qt\6.7.0\msvc2019_64\bin\qmake.exe
QT_PLUGIN_PATH: D:\Qt\6.7.0\msvc2019_64\bin\qmake.exe\plugins
QML2_IMPORT_PATH: D:\Qt\6.7.0\msvc2019_64\bin\qmake.exe\qml
```
* Link to failing test run that explicitly checks the …
> Use path library for path manipulation 

- .github/workflows/test-android.yml
- .github/workflows/test.yml
- action/src/main.ts
Qt wants `QT_HOST_PATH` when cross-compiling with CMake ([docs](https://doc.qt.io/qt-6/cmake-variable-qt-host-path.html), and [relevant code](https://github.com/qt/qtbase/blob/6.8.1/cmake/QtPublicDependencyHelpers.cmake#L275) to prove it reads the environment variable), and one needs to know this path in other cases like running `windeployqt` since it's only present in the host's installation.
I also fixed a regression introduced in 7595e10a17ba076a16a0354ea11c70a0705836a6, where the regex was changed from something like:
`msvc[^/]*_arm64`
To:
`msvc*_arm64`
Before, `*` applied to the preceding `[^/]`, meaning to match 0 or more non-slash characters. The regression made it look for 0 or more `c` characters (followed immediately by an underscore), so it wouldn't be able to match …
> Set QT_HOST_PATH for parallel desktop installations

- action.yml
Changed range ('3.6.x - 3.11.x') of `python-version` to `>=3.9`
* This is the Minimum requirement of [`aqtinstall`](https://github.com/miurahr/aqtinstall?tab=readme-ov-file#requirements)
* Allows the use of higher Python versions available on the associated "GitHub Actions Runner Images" being used.
* "GitHub Actions Runner Images" will have various Python versions removed/in-process of removing [Example 1](https://github.com/actions/runner-images/issues/10893), [Example 2](https://github.com/actions/runner-images/issues/10812)
____
**NOTE:**
Xcode failures are due to `Xcode 14` no longer being available on macOS-14 runner images
See: https://github.com/actions/runner-images/issues/10703
> Adjust `python-version` limits

- action.yml
[This commit](https://github.com/jurplel/install-qt-action/commit/e892482d6820b3e964f0b65c74de60f8014931d5) introduced failures on the `windows-2019` runners. Unless someone can figure out why it's failing with Python 3.13.x, I would propose limiting Python to 3.12.x for now.
If GitHub follows their usual policy, `windows-2019` might go away soon anyway (mid-2025?) after the `windows-2025` runner is out of beta, so this version restriction could be reverted after that.
> Fix error on windows-2019 runners

- action/src/main.ts
Fixes #281. `setuptools` version chosen per recommendation [here](https://github.com/pypa/wheel/issues/660#issuecomment-2775668964), and this eliminates the need to install `wheel`.
> Fix bdist_wheel error

- README.md
- action.yml
- action/action.yml
- action/package-lock.json
- action/package.json
- action/src/main.ts
- Updates to parameters and logic to handle the latest `aqtinstall` versions, making the action once again able to install any version of Qt, WASM and extensions included (`aqtinstall` >=3.2.0)  
- Add full support for installing Qt commercial versions provided you own a Qt account (paid or not). The account is required even if you only download open-source versions (`aqtinstall` >=3.2.2)  
- Updated outdated defaults, and used Qt 6.8.3 as LTS  
- Updated @action/cache to v4 to match Github's update
Since Qt 6.7+, the Qt team decided to make WASM a part of `all_os` as host, with target `wasm`. This is sensible as the WASM version of Qt cannot work on its own and needs a host. To install Qt WASM for the latest versions, the `host` and `target` values must be edited. See examples.  
This …
> Add commercial support, fix WASM and issues with Qt 6.7.+

- .github/workflows/test.yml
- README.md
- action.yml
- action/src/main.ts
Fixes #248. The Linux part is working fine, I already have my `kimageformats-binaries` and `qView` forks using it and building a working aarch64 AppImage. I haven't tested the Windows part since the ARM64 Windows runners aren't public yet.
If anyone needs to use this before the pull request is merged and released, my [install-qt-action fork](https://github.com/jdpurcell/install-qt-action) makes it possible.
> Support ARM64 hosts
